import enum

DB_LOCATION = "users.db"  # TODO: make another way to get location


class Question(enum.Enum):
    AGE = "age"
    GENDER = "gender"
    PREGNANT = "pregnant"
    SPORT = "sport"
    WEIGHT = "weight"

class Nutrient(enum.Enum):
    Al = "Al"
    B = "B"
    B1 = "B1"
    B10 = "B10"
    B12 = "B12"
    Br = "Br"
    Ca = "Ca"
    Cl = "Cl"
    Co = "Co"
    Cr = "Cr"
    Cu = "Cu"
    D = "D"
    F = "F"
    Fe = "Fe"
    I = "I"
    K = "K"
    L = "L"
    Mg = "Mg"
    Mn = "Mn"
    Mo = "Mo"
    N = "N"
    Na = "Na"
    Ni = "Ni"
    P = "P"
    PP = "PP"
    S = "S"
    Se = "Se"
    Si = "Si"
    U = "U"
    V = "V"
    VK = "VK"
    VP = "VP"
    Zn = "Zn"
    A = "A"
    B13 = "B13"
    B2 = "B2"
    B3 = "B3"
    B4 = "B4"
    B6 = "B6"
    B8 = "B8"
    B9 = "B9"
    E = "E"
    H = "H"
    C = "C"
